import type { CoreAgent } from '@/presentation/components/widgets/AgentCard';

export const DEFAULT_AGENTS: CoreAgent[] = [
  {
    id: 'axe-core',
    name: 'axe-core',
    display_name: 'AXE Core',
    role: 'orchestrator',
    description: 'Master intelligence — routes, tools, multi-model orchestration across the HQ desktop.',
    system_prompt: 'You are AXE CORE — the God Mode OS that builds, runs, and controls the entire AXE ecosystem.',
    memory_namespace: 'axe-core',
    toolset: ['router', 'tools', 'memory', 'sphere'],
    model_provider: 'google',
    model_name: 'gemini-3.5-flash',
    status: 'active',
    version: '2.0',
    capabilities: ['routing', 'tools', 'multi-model', 'sphere'],
    supabase_tables: ['conversations', 'memories', 'core_agents'],
    app_url: null,
    tags: ['hq', 'orchestrator'],
  },
  {
    id: 'axe-companion',
    name: 'axe-companion',
    display_name: 'AXE Companion',
    role: 'assistant',
    description: 'Personal AI assistant specialised in trading and investing. Memory lives in Supabase.',
    system_prompt: 'You are AXE Companion — advanced AI personal assistant specialised in trading and investing.',
    memory_namespace: 'companion',
    toolset: ['live', 'per-user', 'rag', 'tool-calling'],
    model_provider: 'google',
    model_name: 'gemini-2.0-flash',
    status: 'active',
    version: '1.0',
    capabilities: ['live', 'per-user', 'rag', 'tool-calling', 'adaptive-ui'],
    supabase_tables: [],
    app_url: null,
    tags: ['companion'],
  },
  {
    id: 'axe-intel',
    name: 'axe-intel',
    display_name: 'AXE Intel',
    role: 'analyst',
    description: 'Market intelligence and signal detection from real-time intel tables.',
    system_prompt: 'You are AXE Intel — market intelligence and signal detection agent.',
    memory_namespace: 'intel',
    toolset: ['market-intel', 'signals', 'real-time'],
    model_provider: 'openrouter',
    model_name: 'claude-3.5-sonnet',
    status: 'active',
    version: '1.0',
    capabilities: ['market-intel', 'signals', 'real-time'],
    supabase_tables: [],
    app_url: null,
    tags: ['intel'],
  },
  {
    id: 'axe-developer',
    name: 'axe-developer',
    display_name: 'AXE Developer',
    role: 'developer',
    description: 'Code generation, review, and deployment across AXE CORE and Companion.',
    system_prompt: 'You are AXE Developer — code generation and deployment agent.',
    memory_namespace: 'developer',
    toolset: ['code', 'deploy', 'github'],
    model_provider: 'openrouter',
    model_name: 'claude-3.5-sonnet',
    status: 'active',
    version: '1.0',
    capabilities: ['code', 'deploy', 'github', 'full-stack'],
    supabase_tables: [],
    app_url: null,
    tags: ['dev'],
  },
  {
    id: 'trading-agent',
    name: 'trading-agent',
    display_name: 'Trading Agent',
    role: 'trader',
    description: 'Demo trading on MetaAPI/MT5 — reads intel, research, and chart context.',
    system_prompt: 'You are the AXE Trading Agent. You trade on demo only, respect risk limits, and explain every decision.',
    memory_namespace: 'trading',
    toolset: ['chart', 'metaapi', 'research', 'risk'],
    model_provider: 'google',
    model_name: 'gemini-3.5-flash',
    status: 'active',
    version: '1.0',
    capabilities: ['demo-trade', 'research', 'risk', 'backtest'],
    supabase_tables: ['trades', 'intel'],
    app_url: null,
    tags: ['trading', 'tab:trading'],
  },
  {
    id: 'browser-agent',
    name: 'browser-agent',
    display_name: 'Browser Agent',
    role: 'assistant',
    description: 'Web browsing, scraping, and research runs inside the Browser tab.',
    system_prompt: 'You are the AXE Browser Agent. Navigate, extract, and summarise pages safely.',
    memory_namespace: 'browser',
    toolset: ['browse', 'scrape', 'extract'],
    model_provider: 'google',
    model_name: 'gemini-3.5-flash',
    status: 'active',
    version: '1.0',
    capabilities: ['browse', 'scrape', 'summarise'],
    supabase_tables: [],
    app_url: null,
    tags: ['browser', 'tab:browser'],
  },
  {
    id: 'thinkthanks-agent',
    name: 'thinkthanks-agent',
    display_name: 'ThinkThanks Agent',
    role: 'analyst',
    description: 'Growth engine — analyse drops, score app fit, BUILD blueprints, INTEGRATE.',
    system_prompt: 'You are the ThinkThanks growth analyst for AXE Core, Companion, AXON Memory, and Trading OS.',
    memory_namespace: 'thinkthanks',
    toolset: ['vision', 'scrape', 'build', 'integrate'],
    model_provider: 'google',
    model_name: 'gemini-3.5-flash',
    status: 'active',
    version: '1.0',
    capabilities: ['vision', 'enrich', 'score', 'build'],
    supabase_tables: [],
    app_url: null,
    tags: ['thinkthanks', 'tab:thinkthanks'],
  },
  {
    id: 'finance-agent',
    name: 'finance-agent',
    display_name: 'Finance Agent',
    role: 'analyst',
    description: 'P&L, books, and finance tab intelligence.',
    system_prompt: 'You are the AXE Finance Agent. Track P&L, books, and financial context.',
    memory_namespace: 'finance',
    toolset: ['ledger', 'reports'],
    model_provider: 'google',
    model_name: 'gemini-3.5-flash',
    status: 'active',
    version: '1.0',
    capabilities: ['pnl', 'books', 'reports'],
    supabase_tables: [],
    app_url: null,
    tags: ['finance', 'tab:finance'],
  },
  {
    id: 'task-manager',
    name: 'task-manager',
    display_name: 'Task Manager',
    role: 'assistant',
    description: 'Mission control tasks — prioritise, schedule, close the loop.',
    system_prompt: 'You are the AXE Task Manager agent.',
    memory_namespace: 'tasks',
    toolset: ['tasks', 'schedule'],
    model_provider: 'google',
    model_name: 'gemini-3.5-flash',
    status: 'active',
    version: '1.0',
    capabilities: ['tasks', 'priority', 'follow-up'],
    supabase_tables: ['tasks'],
    app_url: null,
    tags: ['tasks', 'tab:tasks'],
  },
  {
    id: 'cron-manager',
    name: 'cron-manager',
    display_name: 'Cron Manager',
    role: 'assistant',
    description: 'Scheduled jobs, self-heal checks, and recurring automation.',
    system_prompt: 'You are the AXE Cron Manager agent.',
    memory_namespace: 'cron',
    toolset: ['cron', 'health'],
    model_provider: 'google',
    model_name: 'gemini-3.5-flash',
    status: 'active',
    version: '1.0',
    capabilities: ['schedule', 'self-heal', 'alerts'],
    supabase_tables: [],
    app_url: null,
    tags: ['cron', 'tab:cron'],
  },
  {
    id: 'memory-manager',
    name: 'memory-manager',
    display_name: 'Memory Manager',
    role: 'assistant',
    description: 'Global memory, Obsidian vault, RAG consolidation and decay.',
    system_prompt: 'You are the AXE Memory Manager. Keep the durable brain healthy.',
    memory_namespace: 'memory',
    toolset: ['memory', 'obsidian', 'rag'],
    model_provider: 'google',
    model_name: 'gemini-3.5-flash',
    status: 'active',
    version: '1.0',
    capabilities: ['consolidate', 'decay', 'graph'],
    supabase_tables: ['memories'],
    app_url: null,
    tags: ['memory', 'tab:memory'],
  },
  {
    id: 'app-manager',
    name: 'app-manager',
    display_name: 'App Manager',
    role: 'developer',
    description: 'App registry, integrations, and cross-app surfaces.',
    system_prompt: 'You are the AXE App Manager.',
    memory_namespace: 'apps',
    toolset: ['apps', 'integrations'],
    model_provider: 'google',
    model_name: 'gemini-3.5-flash',
    status: 'active',
    version: '1.0',
    capabilities: ['registry', 'integrations'],
    supabase_tables: [],
    app_url: null,
    tags: ['apps', 'tab:apps'],
  },
];
