import { create } from 'zustand';
import { logMessage } from '@/services/coreDB';
import { classifyQueryDynamic, loadCapabilities, getAgentSystemPrompt, getCapabilityExecutionMode } from '@/services/capabilityService';
import { buildWorkflow, formatBuildResult } from '@/services/workflowBuilder';
import { getSystemSummary, checkAllServices } from '@/services/systemService';
import { getDefaultOllamaModelNames, sortOllamaModelsForCapability } from '@/services/ollamaModelCatalog';
import { getStoredLlmModelRegistry } from '@/services/llmModelRegistryService';
import { loadSetting, saveSetting } from '@/services/userSettingsService';
import { normalizeProviderBaseUrl } from '@/services/providerConnectionDefaults';
import { loadMessages, saveMessage, AXE_USER_ID, loadAllConversations, createNewConversationId } from '@/services/chatPersistence';
import type { ConversationSummary } from '@/services/chatPersistence';
import { isAxeApiConfigured, crewRun, tts } from '@/services/axeCoreApiService';
import { speakWithElevenLabs, speakWithBrowser, stopTTS } from '@/services/elevenLabsService';
